### ISSUE TITLE
Component wont accept camel-cased props

### ISSUE THREAD

**Issue by jaisondavis** [carterbourette/vue-frappe-chart#1]
So if you pass camel-cased props like yMarkers, barOptions etc. the component does not recognize it.

The problem is Vue converts all camelcase props to ymarkers, baroptions etc. So in the parse() function in Chart.vue, these props are registered incorrectly.

BTW thank you for building this. It was very beneficial.

**Comment by carterbourette** [comment]
Hi @jaisondavis thanks for the patch and for reporting.

Discussion about the issue you encountered here (assuming you are include Vue as a script tag):
https://github.com/vuejs/v2.vuejs.org/issues/1807#issuecomment-426549600

Now supporting this lower camel case quirk and kebab case as of `0.1.9`
