### ISSUE TITLE
Docs do not say if it is for Vue 2 or 3

### ISSUE THREAD

**Issue by paul-gaspar** [carterbourette/vue-frappe-chart#2]
Your package looks fantastic! Thanks for the awesome work.

Just there is no hint anywhere if this is made for Vue 2 or 3 (or both?).

**Comment by quiquelhappy** [comment]
i'd also like to know this just by glancing at the readme

**Comment by carterbourette** [comment]
Hi, thank you. I added a note that it should support Vue 2 + 3 now that #3 is resolved.
